#! /usr/bin/bash

# enable and set up latest pnpm
corepack enable
corepack prepare pnpm@latest --activate
SHELL=bash pnpm setup
source /home/user/.bashrc

# install dependencies
cd $PROJECT_SOURCE
pnpm i